# Generated by Django 4.1.7 on 2023-05-20 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.element_category'),
        ),
        migrations.AlterField(
            model_name='element',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Длинна'),
        ),
        migrations.AlterField(
            model_name='element',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Длинна'),
        ),
        migrations.AlterField(
            model_name='element',
            name='manufacturer_country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна производства'),
        ),
        migrations.AlterField(
            model_name='element',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='element',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ширина'),
        ),
    ]
