# Generated by Django 4.1.7 on 2023-05-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_element_category_alter_element_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Высота в м'),
        ),
        migrations.AlterField(
            model_name='element',
            name='image',
            field=models.ImageField(blank=True, default='/static/img/img1.png', null=True, upload_to='img/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='element',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Длинна в м'),
        ),
        migrations.AlterField(
            model_name='element',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Вес в кг'),
        ),
        migrations.AlterField(
            model_name='element',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ширина в м'),
        ),
    ]
